**Numpy Basic Operations**

In [2]:
import numpy as np
array = np.random.randint(1, 101, size =10)
# SUM Operation using Numpy
print(f"array is: {array}")
print("sum of array is: ", np.sum(array))
 # MEAN Operation using Numpy
print("mean of array is: ", np.mean(array))
# MEDIAN Operation using Numpy
print("median of array is: ", np.median(array))
# STANDARD DEVIATION Operation using Numpy
print("std deviation of array is: ",  np.std(array))
# VARIANCE Operation using Numpy
print("variance of array is: ", np.var(array))


array is: [17  5 15 73 83 74 25  1 49 76]
sum of array is:  418
mean of array is:  41.8
median of array is:  37.0
std deviation of array is:  30.925070735569868
variance of array is:  956.3599999999999


**Ascending and Descending of an array**

In [4]:
# Ascendng Array
asc_array = np.sort(array)
print(asc_array)
# Descending Array
desc_array = np.sort(array)[::-1]
print(desc_array)

[ 1  5 15 17 25 49 73 74 76 83]
[83 76 74 73 49 25 17 15  5  1]


**Element-wise Operations**

In [6]:
array1 = np.random.randint(1,101, 15)
print(f"array1: {array1} ")
array2 = np.random.randint(1, 101, 15)
print(f"array 2: {array2}")
addition =np.add(array1, array2)
print(f"addition is: {addition}")
subtract = array1-array2
print(f"after subtracting two arrays: {subtract}")
multiplication = array1*array2
print(f"after multiplication: {multiplication}")
Element_wise_division = array1/array2
print(f"element-wise-division: {Element_wise_division}")

array1: [70 98 58 52 64 57 68 32 35 53 73 29 14 33 99] 
array 2: [23 55 64 33 68 14 41 21 48  7 48 58 71 97 80]
addition is: [ 93 153 122  85 132  71 109  53  83  60 121  87  85 130 179]
after subtracting two arrays: [ 47  43  -6  19  -4  43  27  11 -13  46  25 -29 -57 -64  19]
after multiplication: [1610 5390 3712 1716 4352  798 2788  672 1680  371 3504 1682  994 3201
 7920]
element-wise-division: [3.04347826 1.78181818 0.90625    1.57575758 0.94117647 4.07142857
 1.65853659 1.52380952 0.72916667 7.57142857 1.52083333 0.5
 0.1971831  0.34020619 1.2375    ]


**Scalar Multiplication**

In [8]:
scalar_mul = array1*3
print(scalar_mul)
scalar_mul2 = array2*3
print(scalar_mul2)

[210 294 174 156 192 171 204  96 105 159 219  87  42  99 297]
[ 69 165 192  99 204  42 123  63 144  21 144 174 213 291 240]


**Trigonometric Operations**

In [9]:
sin_value = np.sin(array)
print(f"sin values: {sin_value}")
cosine_val = np.cos(array)
print(f"cosine values: {cosine_val}")
tangent_val = np.tan(array)
print(f"tangent values: {tangent_val}")

sin values: [-0.96139749 -0.95892427  0.65028784 -0.67677196  0.96836446 -0.98514626
 -0.13235175  0.84147098 -0.95375265  0.56610764]
cosine values: [-0.27516334  0.28366219 -0.75968791 -0.73619272  0.24954012  0.17171734
  0.99120281  0.54030231  0.30059254  0.82433133]
tangent values: [ 3.49391565 -3.38051501 -0.8559934   0.9192864   3.88059631 -5.73702254
 -0.13352641  1.55740772 -3.17290855  0.68674769]
